### ISSUE TITLE
GenericDao.Get and EntityDao.GetByBusinessId have inconsistent error behavior

### ISSUE THREAD

**Issue by johannroth** [queoGmbH/csharp-commons.persistence#8]
While GenericDao.Get internally uses `.SingleOrDefault` (so technically return type `TEntity?`), EntityDao.GetByBusinessId uses `.Single`, so it returns `TEntity` and throws an `InvalidOperationException` if no matching entity can be found. Behavior of .Get should probably be consistent.

`.TryGet` or `.GetOrNull` could be used to allow for null to be returned, while `.Get` should always throw, if no entity with the given id can be resolved.
To be able to externally handle the InvalidOperationException on not being able to resolve an entity from a given Id, a custom Exception (e.g. `EntityNotResolvableFromIdException`) could also be added.

**Comment by uoehm** [comment]
Behaviour of Get is now consistent an throws an InvalidOperationException exception. For throwing a special EntityNotFoundException i will create a new issue.
